import { index, layout, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  layout('./routes/_layout.tsx', [
    index('./routes/_index.tsx'),
    route('cockpit', './routes/cockpit/index.tsx'),
    route('my-work', './routes/my-work/index.tsx'),
    route('requirements', './routes/requirements/index.tsx'),
    route('requirements/new', './routes/requirements/new.tsx'),
    route('requirements/:requirementId', './routes/requirements/$requirementId.tsx'),
    route('requirements/:requirementId/evidence', './routes/requirements/$requirementId/evidence.tsx'),
    route('initiatives', './routes/initiatives/index.tsx'),
    route('initiatives/new', './routes/initiatives/new.tsx'),
    route('initiatives/:initiativeId', './routes/initiatives/$initiativeId.tsx'),
    route('initiatives/:initiativeId/evidence', './routes/initiatives/$initiativeId/evidence.tsx'),
    route('tech-debt', './routes/tech-debt/index.tsx'),
    route('tech-debt/new', './routes/tech-debt/new.tsx'),
    route('tech-debt/:techDebtId', './routes/tech-debt/$techDebtId.tsx'),
    route('tech-debt/:techDebtId/evidence', './routes/tech-debt/$techDebtId/evidence.tsx'),
    route('development-plans', './routes/development-plans/index.tsx'),
    route('development-plans/new', './routes/development-plans/new.tsx'),
    route('development-plans/:developmentPlanId', './routes/development-plans/$developmentPlanId.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId', './routes/development-plans/$developmentPlanId/items/$itemId.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/brainstorming', './routes/development-plans/$developmentPlanId/items/$itemId/brainstorming.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/spec', './routes/development-plans/$developmentPlanId/items/$itemId/spec.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/execution-plan', './routes/development-plans/$developmentPlanId/items/$itemId/execution-plan.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/execution', './routes/development-plans/$developmentPlanId/items/$itemId/execution.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/review', './routes/development-plans/$developmentPlanId/items/$itemId/review.tsx'),
    route('development-plans/:developmentPlanId/items/:itemId/qa', './routes/development-plans/$developmentPlanId/items/$itemId/qa.tsx'),
    route('specs-plans', './routes/specs-plans/index.tsx'),
    route('bugs', './routes/bugs/index.tsx'),
    route('bugs/new', './routes/bugs/new.tsx'),
    route('bugs/:bugId', './routes/bugs/$bugId.tsx'),
    route('bugs/:bugId/evidence', './routes/bugs/$bugId/evidence.tsx'),
    route('board', './routes/board/index.tsx'),
    route('executions', './routes/executions/index.tsx'),
    route('executions/:executionId', './routes/executions/$executionId.tsx'),
    route('releases', './routes/releases/index.tsx'),
    route('releases/:releaseId', './routes/releases/$releaseId.tsx'),
    route('releases/:releaseId/evidence', './routes/releases/$releaseId/evidence.tsx'),
    route('reports', './routes/reports/index.tsx'),
    route('reports/delivery', './routes/reports/delivery.tsx'),
    route('reports/quality', './routes/reports/quality.tsx'),
    route('reports/release-readiness', './routes/reports/release-readiness.tsx'),
    route('reports/observation', './routes/reports/observation.tsx'),
    route('dev-tools', './routes/dev-tools/index.tsx'),
    route('*', './routes/_not-found.tsx'),
  ]),
] satisfies RouteConfig;
