import { index, layout, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  layout('./routes/_layout.tsx', [
    index('./routes/_index.tsx'),
    route('dashboard', './routes/dashboard/index.tsx'),
    route('my-work', './routes/my-work/index.tsx'),
    route('requirements', './routes/requirements/index.tsx'),
    route('requirements/new', './routes/requirements/new.tsx'),
    route('requirements/:requirementId', './routes/requirements/$requirementId.tsx'),
    route('requirements/:requirementId/evidence', './routes/requirements/$requirementId/evidence.tsx'),
    route('initiatives', './routes/initiatives/index.tsx'),
    route('initiatives/new', './routes/initiatives/new.tsx'),
    route('initiatives/:initiativeId', './routes/initiatives/$initiativeId.tsx'),
    route('initiatives/:initiativeId/evidence', './routes/initiatives/$initiativeId/evidence.tsx'),
    route('tech-debt', './routes/tech-debt/index.tsx'),
    route('tech-debt/new', './routes/tech-debt/new.tsx'),
    route('tech-debt/:techDebtId', './routes/tech-debt/$techDebtId.tsx'),
    route('tech-debt/:techDebtId/evidence', './routes/tech-debt/$techDebtId/evidence.tsx'),
    route('specs-plans', './routes/specs-plans/index.tsx'),
    route('bugs', './routes/bugs/index.tsx'),
    route('bugs/new', './routes/bugs/new.tsx'),
    route('bugs/:bugId', './routes/bugs/$bugId.tsx'),
    route('bugs/:bugId/evidence', './routes/bugs/$bugId/evidence.tsx'),
    route('board', './routes/board/index.tsx'),
    route('releases', './routes/releases/index.tsx'),
    route('releases/:releaseId', './routes/releases/$releaseId.tsx'),
    route('releases/:releaseId/evidence', './routes/releases/$releaseId/evidence.tsx'),
    route('reports', './routes/reports/index.tsx'),
    route('reports/delivery', './routes/reports/delivery.tsx'),
    route('reports/quality', './routes/reports/quality.tsx'),
    route('reports/release-readiness', './routes/reports/release-readiness.tsx'),
    route('reports/observation', './routes/reports/observation.tsx'),
    route('reports/replay', './routes/reports/replay.tsx'),
    route('dev-tools', './routes/dev-tools/index.tsx'),
  ]),
] satisfies RouteConfig;
