import type { MyWorkQuery, ProjectManagementListQuery } from './query';
import type { AttachmentOwnerObjectType, ListProductQuery, ProductLaneId, ProductLaneQuery, SessionOperationsHealthQuery } from './types';

export const normalizeProductLaneQuery = (query: ProductLaneQuery): ProductLaneQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.execution_owner_actor_id === undefined ? {} : { execution_owner_actor_id: query.execution_owner_actor_id }),
  ...(query.reviewer_actor_id === undefined ? {} : { reviewer_actor_id: query.reviewer_actor_id }),
  ...(query.qa_owner_actor_id === undefined ? {} : { qa_owner_actor_id: query.qa_owner_actor_id }),
  ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
  ...(query.kind === undefined ? {} : { kind: query.kind }),
  ...(query.phase === undefined ? {} : { phase: query.phase }),
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
  ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.blocked === undefined ? {} : { blocked: query.blocked }),
  ...(query.stale === undefined ? {} : { stale: query.stale }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeProductRegistryQuery = (query: ListProductQuery): ListProductQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.phase === undefined ? {} : { phase: query.phase }),
  ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
  ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.execution_owner_actor_id === undefined ? {} : { execution_owner_actor_id: query.execution_owner_actor_id }),
  ...(query.reviewer_actor_id === undefined ? {} : { reviewer_actor_id: query.reviewer_actor_id }),
  ...(query.qa_owner_actor_id === undefined ? {} : { qa_owner_actor_id: query.qa_owner_actor_id }),
  ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
  ...(query.spec_id === undefined ? {} : { spec_id: query.spec_id }),
  ...(query.plan_id === undefined ? {} : { plan_id: query.plan_id }),
  ...(query.spec_revision_id === undefined ? {} : { spec_revision_id: query.spec_revision_id }),
  ...(query.plan_revision_id === undefined ? {} : { plan_revision_id: query.plan_revision_id }),
  ...(query.execution_id === undefined ? {} : { execution_id: query.execution_id }),
  ...(query.release_id === undefined ? {} : { release_id: query.release_id }),
  ...(query.surface_type === undefined ? {} : { surface_type: query.surface_type }),
  ...(query.executor_type === undefined ? {} : { executor_type: query.executor_type }),
  ...(query.decision === undefined ? {} : { decision: query.decision }),
  ...(query.blocked === undefined ? {} : { blocked: query.blocked }),
  ...(query.stale === undefined ? {} : { stale: query.stale }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeMyWorkQuery = (query: MyWorkQuery): MyWorkQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeProjectManagementListQuery = (query: ProjectManagementListQuery): ProjectManagementListQuery => ({
  project_id: query.project_id,
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.execution_owner_actor_id === undefined ? {} : { execution_owner_actor_id: query.execution_owner_actor_id }),
  ...(query.reviewer_actor_id === undefined ? {} : { reviewer_actor_id: query.reviewer_actor_id }),
  ...(query.qa_owner_actor_id === undefined ? {} : { qa_owner_actor_id: query.qa_owner_actor_id }),
  ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeSessionOperationsHealthQuery = (
  query: SessionOperationsHealthQuery,
): SessionOperationsHealthQuery => ({
  ...(query.development_plan_id === undefined ? {} : { development_plan_id: query.development_plan_id }),
  ...(query.development_plan_item_id === undefined ? {} : { development_plan_item_id: query.development_plan_item_id }),
  ...(query.project_id === undefined ? {} : { project_id: query.project_id }),
  ...(query.workflow_id === undefined ? {} : { workflow_id: query.workflow_id }),
  ...(query.codex_session_id === undefined ? {} : { codex_session_id: query.codex_session_id }),
  ...(query.worker_id === undefined ? {} : { worker_id: query.worker_id }),
  ...(query.state === undefined ? {} : { state: query.state }),
  ...(query.severity === undefined ? {} : { severity: query.severity }),
  ...(query.recovered_state === undefined ? {} : { recovered_state: query.recovered_state }),
  ...(query.candidate_only === undefined ? {} : { candidate_only: query.candidate_only }),
  ...(query.include_recovered === undefined ? {} : { include_recovered: query.include_recovered }),
  ...(query.include_unrecoverable === undefined ? {} : { include_unrecoverable: query.include_unrecoverable }),
  ...(query.min_lease_age_seconds === undefined ? {} : { min_lease_age_seconds: query.min_lease_age_seconds }),
  ...(query.max_lease_age_seconds === undefined ? {} : { max_lease_age_seconds: query.max_lease_age_seconds }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const queryKeys = {
  dashboard: (query: ListProductQuery) => ['dashboard', normalizeProductRegistryQuery(query)],
  developmentPlans: (query: ListProductQuery) => ['development-plans', normalizeProductRegistryQuery(query)],
  developmentPlan: (developmentPlanId: string | undefined) => ['development-plan', developmentPlanId],
  developmentPlanItem: (developmentPlanId: string | undefined, itemId: string | undefined) => [
    'development-plan-item',
    developmentPlanId,
    itemId,
  ],
  developmentPlanItemRevisions: (developmentPlanId: string | undefined, itemId: string | undefined) => [
    'development-plan-item-revisions',
    developmentPlanId,
    itemId,
  ],
  planItemWorkflow: (workflowId: string | undefined) => ['plan-item-workflow', workflowId],
  boundarySummaryRevisions: (boundarySummaryId: string | undefined) => ['boundary-summary-revisions', boundarySummaryId],
  executions: (query: ListProductQuery) => ['executions', normalizeProductRegistryQuery(query)],
  execution: (executionId: string | undefined) => ['execution', executionId],
  codeReviewHandoffs: (query: ListProductQuery) => ['code-review-handoffs', normalizeProductRegistryQuery(query)],
  qaHandoffs: (query: ListProductQuery) => ['qa-handoffs', normalizeProductRegistryQuery(query)],
  sessionOperationsHealth: (query: SessionOperationsHealthQuery) => [
    'session-operations-health',
    normalizeSessionOperationsHealthQuery(query),
  ],
  sessionOperationsAudit: (sessionId: string | undefined) => ['session-operations-audit', sessionId],
  planItemSessionDiagnostics: (planItemId: string | undefined) => ['plan-item-session-diagnostics', planItemId],
  myWork: (query: MyWorkQuery) => ['my-work', normalizeMyWorkQuery(query)],
  requirements: (query: ProjectManagementListQuery) => ['requirements', normalizeProjectManagementListQuery(query)],
  requirement: (requirementId: string | undefined) => ['requirement', requirementId],
  initiatives: (query: ProjectManagementListQuery) => ['initiatives', normalizeProjectManagementListQuery(query)],
  initiative: (initiativeId: string | undefined) => ['initiative', initiativeId],
  techDebt: (query: ProjectManagementListQuery) => ['tech-debt', normalizeProjectManagementListQuery(query)],
  techDebtDetail: (techDebtId: string | undefined) => ['tech-debt-detail', techDebtId],
  bugs: (query: ProjectManagementListQuery) => ['bugs', normalizeProjectManagementListQuery(query)],
  bug: (bugId: string | undefined) => ['bug', bugId],
  board: (query: ListProductQuery) => ['board', normalizeProductRegistryQuery(query)],
  report: (reportId: string, query: ListProductQuery) => ['report', reportId, normalizeProductRegistryQuery(query)],
  releaseReadiness: (releaseId: string | undefined, projectId: string) => ['release-readiness', releaseId, { project_id: projectId }],
  productLane: (laneId: ProductLaneId, query: ProductLaneQuery) => ['product-lanes', laneId, normalizeProductLaneQuery(query)],
  pipeline: (projectId: string) => ['pipeline', { projectId }],
  workItem: (workItemId: string) => ['work-item', workItemId],
  documentReviewQueue: (query: Pick<ListProductQuery, 'project_id' | 'cursor' | 'limit'>) => ['document-review-queue', query],
  spec: (specId: string) => ['spec', specId],
  specRevisions: (specId: string) => ['spec-revisions', specId],
  specRevision: (revisionId: string | undefined) => ['spec-revision', revisionId],
  plan: (planId: string) => ['plan', planId],
  planRevisions: (planId: string) => ['plan-revisions', planId],
  planRevision: (revisionId: string | undefined) => ['plan-revision', revisionId],
  package: (packageId: string) => ['package', packageId],
  runEvents: (runSessionId: string, actorId: string) => ['run-events', runSessionId, { actorId }],
  run: (runSessionId: string) => ['run', runSessionId],
  releases: (query: { project_id: string; release_owner_actor_id?: string; phase?: string; gate_state?: string; resolution?: string; cursor?: string; limit?: number }) => [
    'releases',
    {
      project_id: query.project_id,
      ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
      ...(query.phase === undefined ? {} : { phase: query.phase }),
      ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
      ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
      ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
      ...(query.limit === undefined ? {} : { limit: query.limit }),
    },
  ],
  releaseCockpit: (releaseId: string) => ['release-cockpit', releaseId],
  attachments: (query: { object_type: AttachmentOwnerObjectType; object_id: string }) => [
    'attachments',
    { object_type: query.object_type, object_id: query.object_id },
  ],
  attachment: (attachmentId: string | undefined) => ['attachment', attachmentId],
  attachmentRender: (attachmentId: string, disposition: 'inline' | 'download') => ['attachment-render', attachmentId, { disposition }],
  markdownDocument: (input: { object_type: string; object_id: string; validation_version: string }) => [
    'markdown-document',
    {
      object_type: input.object_type,
      object_id: input.object_id,
      validation_version: input.validation_version,
    },
  ],
} as const;
