import type { MyWorkQuery, ProductWorkItemRegistryQuery, ProjectManagementListQuery } from './query';
import type { AttachmentOwnerObjectType, ListProductQuery, ProductLaneId, ProductLaneQuery } from './types';

export const normalizeProductLaneQuery = (query: ProductLaneQuery): ProductLaneQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.execution_owner_actor_id === undefined ? {} : { execution_owner_actor_id: query.execution_owner_actor_id }),
  ...(query.reviewer_actor_id === undefined ? {} : { reviewer_actor_id: query.reviewer_actor_id }),
  ...(query.qa_owner_actor_id === undefined ? {} : { qa_owner_actor_id: query.qa_owner_actor_id }),
  ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
  ...(query.kind === undefined ? {} : { kind: query.kind }),
  ...(query.phase === undefined ? {} : { phase: query.phase }),
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
  ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.blocked === undefined ? {} : { blocked: query.blocked }),
  ...(query.stale === undefined ? {} : { stale: query.stale }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeProductRegistryQuery = (query: ListProductQuery): ListProductQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.phase === undefined ? {} : { phase: query.phase }),
  ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
  ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.execution_owner_actor_id === undefined ? {} : { execution_owner_actor_id: query.execution_owner_actor_id }),
  ...(query.reviewer_actor_id === undefined ? {} : { reviewer_actor_id: query.reviewer_actor_id }),
  ...(query.qa_owner_actor_id === undefined ? {} : { qa_owner_actor_id: query.qa_owner_actor_id }),
  ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
  ...(query.spec_id === undefined ? {} : { spec_id: query.spec_id }),
  ...(query.plan_id === undefined ? {} : { plan_id: query.plan_id }),
  ...(query.spec_revision_id === undefined ? {} : { spec_revision_id: query.spec_revision_id }),
  ...(query.plan_revision_id === undefined ? {} : { plan_revision_id: query.plan_revision_id }),
  ...(query.execution_package_id === undefined ? {} : { execution_package_id: query.execution_package_id }),
  ...(query.run_session_id === undefined ? {} : { run_session_id: query.run_session_id }),
  ...(query.review_packet_id === undefined ? {} : { review_packet_id: query.review_packet_id }),
  ...(query.release_id === undefined ? {} : { release_id: query.release_id }),
  ...(query.surface_type === undefined ? {} : { surface_type: query.surface_type }),
  ...(query.executor_type === undefined ? {} : { executor_type: query.executor_type }),
  ...(query.decision === undefined ? {} : { decision: query.decision }),
  ...(query.blocked === undefined ? {} : { blocked: query.blocked }),
  ...(query.stale === undefined ? {} : { stale: query.stale }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeProductWorkItemRegistryQuery = (
  query: ProductWorkItemRegistryQuery,
): ProductWorkItemRegistryQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.phase === undefined ? {} : { phase: query.phase }),
  ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
  ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.blocked === undefined ? {} : { blocked: query.blocked }),
  ...(query.stale === undefined ? {} : { stale: query.stale }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeMyWorkQuery = (query: MyWorkQuery): MyWorkQuery => ({
  project_id: query.project_id,
  ...(query.actor_id === undefined ? {} : { actor_id: query.actor_id }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const normalizeProjectManagementListQuery = (query: ProjectManagementListQuery): ProjectManagementListQuery => ({
  project_id: query.project_id,
  ...(query.status === undefined ? {} : { status: query.status }),
  ...(query.risk === undefined ? {} : { risk: query.risk }),
  ...(query.driver_actor_id === undefined ? {} : { driver_actor_id: query.driver_actor_id }),
  ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  ...(query.limit === undefined ? {} : { limit: query.limit }),
});

export const queryKeys = {
  myWork: (query: MyWorkQuery) => ['my-work', normalizeMyWorkQuery(query)],
  requirements: (query: ProjectManagementListQuery) => ['requirements', normalizeProjectManagementListQuery(query)],
  requirement: (requirementId: string | undefined) => ['requirement', requirementId],
  initiatives: (query: ProjectManagementListQuery) => ['initiatives', normalizeProjectManagementListQuery(query)],
  initiative: (initiativeId: string | undefined) => ['initiative', initiativeId],
  techDebt: (query: ProjectManagementListQuery) => ['tech-debt', normalizeProjectManagementListQuery(query)],
  techDebtDetail: (techDebtId: string | undefined) => ['tech-debt-detail', techDebtId],
  tasks: (query: ProjectManagementListQuery) => ['tasks', normalizeProjectManagementListQuery(query)],
  task: (taskId: string | undefined) => ['task', taskId],
  bugs: (query: ProjectManagementListQuery) => ['bugs', normalizeProjectManagementListQuery(query)],
  bug: (bugId: string | undefined) => ['bug', bugId],
  productLane: (laneId: ProductLaneId, query: ProductLaneQuery) => ['product-lanes', laneId, normalizeProductLaneQuery(query)],
  pipeline: (projectId: string) => ['pipeline', { projectId }],
  workItems: (projectId: string) => ['work-items', { projectId }],
  productWorkItems: (query: ProductWorkItemRegistryQuery) => ['product-work-items', normalizeProductWorkItemRegistryQuery(query)],
  workItem: (workItemId: string) => ['work-item', workItemId],
  workItemCockpit: (workItemId: string | undefined, lane?: ProductLaneId) =>
    lane === undefined ? ['work-item-cockpit', workItemId] : ['work-item-cockpit', workItemId, { lane }],
  workItemReplay: (workItemId: string | undefined) => ['work-item-replay', workItemId],
  specs: (query: ListProductQuery) => ['specs', normalizeProductRegistryQuery(query)],
  spec: (specId: string) => ['spec', specId],
  specRevisions: (specId: string) => ['spec-revisions', specId],
  specReplay: (specId: string | undefined) => ['spec-replay', specId],
  specRevision: (revisionId: string | undefined) => ['spec-revision', revisionId],
  plans: (query: ListProductQuery) => ['plans', normalizeProductRegistryQuery(query)],
  plan: (planId: string) => ['plan', planId],
  planRevisions: (planId: string) => ['plan-revisions', planId],
  planReplay: (planId: string | undefined) => ['plan-replay', planId],
  planRevision: (revisionId: string | undefined) => ['plan-revision', revisionId],
  packages: (query: ListProductQuery) => ['packages', normalizeProductRegistryQuery(query)],
  package: (packageId: string) => ['package', packageId],
  packageRuntimeReadiness: (packageId: string | undefined) => ['package-runtime-readiness', packageId],
  taskPackageEvidence: (taskId: string | undefined, packageId: string | undefined) => ['task-package-evidence', taskId, packageId],
  taskRunEvidence: (taskId: string | undefined, runSessionId: string | undefined) => ['task-run-evidence', taskId, runSessionId],
  taskReviewEvidence: (taskId: string | undefined, reviewPacketId: string | undefined) => ['task-review-evidence', taskId, reviewPacketId],
  runs: (query: ListProductQuery) => ['runs', normalizeProductRegistryQuery(query)],
  runEvents: (runSessionId: string, actorId: string) => ['run-events', runSessionId, { actorId }],
  run: (runSessionId: string) => ['run', runSessionId],
  reviews: (projectId: string) => ['reviews', { projectId }],
  reviewPackets: (query: ListProductQuery) => ['review-packets', normalizeProductRegistryQuery(query)],
  review: (reviewPacketId: string | undefined) => ['review', reviewPacketId],
  reviewPacketReplay: (reviewPacketId: string) => ['review-packet-replay', reviewPacketId],
  releases: (query: { project_id: string; release_owner_actor_id?: string; phase?: string; gate_state?: string; resolution?: string; cursor?: string; limit?: number }) => [
    'releases',
    {
      project_id: query.project_id,
      ...(query.release_owner_actor_id === undefined ? {} : { release_owner_actor_id: query.release_owner_actor_id }),
      ...(query.phase === undefined ? {} : { phase: query.phase }),
      ...(query.gate_state === undefined ? {} : { gate_state: query.gate_state }),
      ...(query.resolution === undefined ? {} : { resolution: query.resolution }),
      ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
      ...(query.limit === undefined ? {} : { limit: query.limit }),
    },
  ],
  releaseCockpit: (releaseId: string) => ['release-cockpit', releaseId],
  releaseReplay: (releaseId: string) => ['release-replay', releaseId],
  executionPackageReplay: (executionPackageId: string) => ['execution-package-replay', executionPackageId],
  attachments: (query: { object_type: AttachmentOwnerObjectType; object_id: string }) => [
    'attachments',
    { object_type: query.object_type, object_id: query.object_id },
  ],
  attachment: (attachmentId: string | undefined) => ['attachment', attachmentId],
  attachmentRender: (attachmentId: string, disposition: 'inline' | 'download') => ['attachment-render', attachmentId, { disposition }],
  markdownDocument: (input: { object_type: string; object_id: string; validation_version: string }) => [
    'markdown-document',
    {
      object_type: input.object_type,
      object_id: input.object_id,
      validation_version: input.validation_version,
    },
  ],
} as const;
